version: '3.7'
services:
  er-build-module:
    image: neg2led/er-build-module:latest
    build:
      context: ./docker
      target: module-builder
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./modules
        target: /root/modules

  er-build:
    image: neg2led/er-build:latest
    build:
      context: ./docker
      target: builder
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /root/repo
