version: '3.7'
services:
  kmod-builder:
    image: neg2led/er-kmod-builder:latest
    build:
      context: .
      target: kmod-builder

  builder:
    image: neg2led/er-kernel-builder:latest
    build:
      context: .
      target: builder
